[package]
name = "sc-chain-spec"
version = "19.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Substrate chain configurations."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
memmap2 = "0.5.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.85"
sc-client-api = { version = "20.0.0", path = "../api" }
sc-chain-spec-derive = { version = "5.0.0", path = "./derive" }
sc-executor = { version = "0.24.0", path = "../executor" }
sc-network = { version = "0.26.0", path = "../network" }
sc-telemetry = { version = "8.0.0", path = "../telemetry" }
sp-blockchain = { version = "20.0.0", path = "../../primitives/blockchain" }
sp-core = { version = "19.0.0", path = "../../primitives/core" }
sp-runtime = { version = "22.0.0", path = "../../primitives/runtime" }
sp-state-machine = { version = "0.26.0", path = "../../primitives/state-machine" }
