[package]
name = "sc-rpc-spec-v2"
version = "0.26.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Substrate RPC interface v2."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpsee = { version = "0.16.2", features = ["client-core", "server", "macros"] }
# Internal chain structures for "chain_spec".
sc-chain-spec = { version = "19.0.0", path = "../chain-spec" }
# Pool for submitting extrinsics required by "transaction"
sc-transaction-pool-api = { version = "20.0.0", path = "../transaction-pool/api" }
sp-core = { version = "19.0.0", path = "../../primitives/core" }
sp-runtime = { version = "22.0.0", path = "../../primitives/runtime" }
sp-api = { version = "18.0.0", path = "../../primitives/api" }
sp-blockchain = { version = "20.0.0", path = "../../primitives/blockchain" }
sp-version = { version = "20.0.0", path = "../../primitives/version" }
sc-client-api = { version = "20.0.0", path = "../api" }
codec = { package = "parity-scale-codec", version = "3.2.2" }
thiserror = "1.0"
serde = "1.0"
hex = "0.4"
futures = "0.3.21"
parking_lot = "0.12.1"
tokio-stream = { version = "0.1", features = ["sync"] }
array-bytes = "4.1"
log = "0.4.17"
futures-util = { version = "0.3.19", default-features = false }

[dev-dependencies]
serde_json = "1.0"
tokio = { version = "1.22.0", features = ["macros"] }
substrate-test-runtime-client = { version = "2.0.0", path = "../../test-utils/runtime/client" }
substrate-test-runtime = { version = "2.0.0", path = "../../test-utils/runtime" }
sp-consensus = { version = "0.24.0", path = "../../primitives/consensus/common" }
sp-maybe-compressed-blob = { version = "5.0.0", path = "../../primitives/maybe-compressed-blob" }
sc-block-builder = { version = "0.25.0", path = "../block-builder" }
sc-utils = { version = "7.0.0", path = "../utils" }
assert_matches = "1.3.0"
