[package]
name = "pallet-beefy-mmr"
version = "20.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
description = "BEEFY + MMR runtime utilities"
repository = "https://github.com/paritytech/substrate"
homepage = "https://substrate.io"

[dependencies]
array-bytes = { version = "4.1", optional = true }
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false, features = ["derive"] }
log = { version = "0.4.17", default-features = false }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
serde = { version = "1.0.136", optional = true }
binary-merkle-tree = { version = "6.0.0", default-features = false, path = "../../utils/binary-merkle-tree" }
frame-support = { version = "20.0.0", default-features = false, path = "../support" }
frame-system = { version = "20.0.0", default-features = false, path = "../system" }
pallet-beefy = { version = "20.0.0", default-features = false, path = "../beefy" }
pallet-mmr = { version = "19.0.0", default-features = false, path = "../merkle-mountain-range" }
pallet-session = { version = "20.0.0", default-features = false, path = "../session" }
sp-consensus-beefy = { version = "5.0.0", default-features = false, path = "../../primitives/consensus/beefy" }
sp-core = { version = "19.0.0", default-features = false, path = "../../primitives/core" }
sp-io = { version = "21.0.0", default-features = false, path = "../../primitives/io" }
sp-runtime = { version = "22.0.0", default-features = false, path = "../../primitives/runtime" }
sp-std = { version = "7.0.0", default-features = false, path = "../../primitives/std" }
sp-api = { version = "18.0.0", default-features = false, path = "../../primitives/api" }

[dev-dependencies]
array-bytes = "4.1"
sp-staking = { version = "18.0.0", path = "../../primitives/staking" }

[features]
default = ["std"]
std = [
	"array-bytes",
	"binary-merkle-tree/std",
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"pallet-beefy/std",
	"pallet-mmr/std",
	"pallet-session/std",
	"scale-info/std",
	"serde",
	"sp-consensus-beefy/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-api/std",
]
try-runtime = ["frame-support/try-runtime"]
