[package]
description = "Substrate network common"
name = "sc-network-common"
version = "0.25.0"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
documentation = "https://docs.rs/sc-network-sync"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
prost-build = "0.11"

[dependencies]
array-bytes = "4.1"
async-trait = "0.1.57"
bitflags = "1.3.2"
bytes = "1"
codec = { package = "parity-scale-codec", version = "3.2.2", features = [
	"derive",
] }
futures = "0.3.21"
futures-timer = "3.0.2"
libp2p = { version = "0.50.0", features = ["request-response", "kad"] }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", version = "0.12.0", path = "../../../utils/prometheus" }
smallvec = "1.8.0"
sc-consensus = { version = "0.25.0", path = "../../consensus/common" }
sc-peerset = { version = "8.0.0", path = "../../peerset" }
sc-utils = { version = "7.0.0", path = "../../utils" }
serde = { version = "1.0.136", features = ["derive"] }
sp-consensus = { version = "0.24.0", path = "../../../primitives/consensus/common" }
sp-consensus-grandpa = { version = "5.0.0", path = "../../../primitives/consensus/grandpa" }
sp-runtime = { version = "22.0.0", path = "../../../primitives/runtime" }
sp-blockchain = { version = "20.0.0", path = "../../../primitives/blockchain" }
thiserror = "1.0"
zeroize = "1.4.3"

[dev-dependencies]
tempfile = "3.1.0"
