[package]
name = "sc-consensus-grandpa"
version = "0.11.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Integration of the GRANDPA finality gadget into substrate."
documentation = "https://docs.rs/sc-consensus-grandpa"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
ahash = "0.8.2"
array-bytes = "4.1"
async-trait = "0.1.57"
dyn-clone = "1.0"
finality-grandpa = { version = "0.16.2", features = ["derive-codec"] }
futures = "0.3.21"
futures-timer = "3.0.1"
log = "0.4.17"
parity-scale-codec = { version = "3.2.2", features = ["derive"] }
parking_lot = "0.12.1"
rand = "0.8.5"
serde_json = "1.0.85"
thiserror = "1.0"
fork-tree = { version = "7.0.0", path = "../../../utils/fork-tree" }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", version = "0.12.0", path = "../../../utils/prometheus" }
sc-block-builder = { version = "0.25.0", path = "../../block-builder" }
sc-chain-spec = { version = "19.0.0", path = "../../../client/chain-spec" }
sc-client-api = { version = "20.0.0", path = "../../api" }
sc-consensus = { version = "0.25.0", path = "../common" }
sc-network = { version = "0.26.0", path = "../../network" }
sc-network-gossip = { version = "0.26.0", path = "../../network-gossip" }
sc-network-common = { version = "0.25.0", path = "../../network/common" }
sc-telemetry = { version = "8.0.0", path = "../../telemetry" }
sc-utils = { version = "7.0.0", path = "../../utils" }
sp-api = { version = "18.0.0", path = "../../../primitives/api" }
sp-application-crypto = { version = "21.0.0", path = "../../../primitives/application-crypto" }
sp-arithmetic = { version = "15.0.0", path = "../../../primitives/arithmetic" }
sp-blockchain = { version = "20.0.0", path = "../../../primitives/blockchain" }
sp-consensus = { version = "0.24.0", path = "../../../primitives/consensus/common" }
sp-core = { version = "19.0.0", path = "../../../primitives/core" }
sp-consensus-grandpa = { version = "5.0.0", path = "../../../primitives/consensus/grandpa" }
sp-keystore = { version = "0.25.0", path = "../../../primitives/keystore" }
sp-runtime = { version = "22.0.0", path = "../../../primitives/runtime" }

[dev-dependencies]
assert_matches = "1.3.0"
finality-grandpa = { version = "0.16.2", features = ["derive-codec", "test-helpers"] }
serde = "1.0.136"
tokio = "1.22.0"
sc-network = { version = "0.26.0", path = "../../network" }
sc-network-test = { version = "0.8.0", path = "../../network/test" }
sp-keyring = { version = "22.0.0", path = "../../../primitives/keyring" }
sp-tracing = { version = "9.0.0", path = "../../../primitives/tracing" }
substrate-test-runtime-client = { version = "2.0.0", path = "../../../test-utils/runtime/client" }
